In [23]:
import pandas as pd
import glob

def parse_log_file(logfile):
    """Parse a single log file and return its data as a dictionary."""
    data = {
        "instance": None,
        "status": None,
        "time": None,
        "cost": None,
        "weighted": None
    }
    with open(logfile, 'r') as f:
        lines = f.readlines()
        # Assuming the format in each log file is consistent with the one provided
        first_line = lines[0].strip().split()
        
        data["instance"] = first_line[0]
        data["status"] = first_line[1]
        data["time"] = float(first_line[2])
        data["cost"] = float(first_line[3]) if len(first_line) > 3 else None
        data["weighted"] = ".weighted.log" in logfile

    return data

def collect_log_data(log_directory):
    """Collect data from all .log files in the specified directory into a DataFrame."""
    log_files = glob.glob(f"{log_directory}/*.log")
    log_data = []

    # Parse each log file and add its data to the list
    for logfile in log_files:
        parsed_data = parse_log_file(logfile)
        log_data.append(parsed_data)

    # Convert the list of dictionaries into a DataFrame
    df = pd.DataFrame(log_data)
    return df

In [24]:
df = collect_log_data("itc2007")
df_unweighted = df[~df["weighted"]][["instance","status","time"]].copy()
df_weighted = df[df["weighted"]][["instance","status","time","cost"]].copy()
df_unweighted.sort_values(by="instance", inplace=True)
df_weighted.sort_values(by="instance", inplace=True)

In [25]:
df_unweighted

              instance   status        time
4   itc2007/comp01.ctt  timeout  600.000000
30  itc2007/comp02.ctt    UNSAT    0.061466
19  itc2007/comp03.ctt    UNSAT    0.048963
10  itc2007/comp04.ctt    UNSAT    0.056402
14  itc2007/comp05.ctt    UNSAT    0.021112
29  itc2007/comp06.ctt    UNSAT    0.000024
9   itc2007/comp07.ctt    UNSAT    0.320666
36  itc2007/comp08.ctt    UNSAT    0.084108
11  itc2007/comp09.ctt    UNSAT    0.053764
32  itc2007/comp10.ctt    UNSAT    0.124466
38  itc2007/comp11.ctt      SAT    1.181121
27  itc2007/comp12.ctt    UNSAT    0.000018
21  itc2007/comp13.ctt    UNSAT    0.069190
2   itc2007/comp14.ctt    UNSAT    0.073685
12  itc2007/comp15.ctt    UNSAT    0.051530
6   itc2007/comp16.ctt    UNSAT    0.000026
35  itc2007/comp17.ctt    UNSAT    0.000019
18  itc2007/comp18.ctt    UNSAT    0.016606
34  itc2007/comp19.ctt    UNSAT    0.000022
15  itc2007/comp20.ctt    UNSAT    0.178183
37  itc2007/comp21.ctt    UNSAT    0.083997

In [26]:
df_weighted

              instance   status        time   cost
13  itc2007/comp01.ctt  timeout  600.000000    NaN
24  itc2007/comp02.ctt      SAT  136.280722   24.0
40  itc2007/comp03.ctt  timeout  600.000000    NaN
23  itc2007/comp04.ctt      SAT    1.445253   36.0
17  itc2007/comp05.ctt    UNSAT    0.294007  186.0
20  itc2007/comp06.ctt      SAT   37.962878   28.0
8   itc2007/comp07.ctt  timeout  600.000000    NaN
1   itc2007/comp08.ctt      SAT    2.346221   38.0
33  itc2007/comp09.ctt  timeout  600.000000    NaN
28  itc2007/comp10.ctt      SAT  187.608049    4.0
7   itc2007/comp11.ctt      SAT    0.471647    0.0
25  itc2007/comp12.ctt  timeout  600.000000    NaN
22  itc2007/comp13.ctt      SAT    1.407659   62.0
41  itc2007/comp14.ctt      SAT    2.957867   54.0
16  itc2007/comp15.ctt  timeout  600.000000    NaN
26  itc2007/comp16.ctt      SAT    3.130460   22.0
3   itc2007/comp17.ctt      SAT   20.925956   60.0
31  itc2007/comp18.ctt  timeout  600.000000    NaN
39  itc2007/comp19.ctt      SAT   26.942130   58.0
0   itc2007/comp20.ctt      SAT  151.634341    4.0
5   itc2007/comp21.ctt  timeout  600.000000    NaN